In [1]:
import subprocess

# Define the notebook filename and repository
notebook_filename = "Data_Overview.ipynb"
repo_url = "https://github.com/your-username/your-repo.git"

# Git commands to push the Jupyter Notebook
commands = [
    "git init",
    f"git add {notebook_filename}",
    'git commit -m "Added Jupyter Notebook"',
    f"git remote add origin {repo_url}",
    "git branch -M main",
    "git push -u origin main"
]

for command in commands:
    run_command(command)

print("✅ Jupyter Notebook successfully pushed to GitHub!")

NameError: name 'run_command' is not defined

# Data Overview: Summarize and Preview Your Dataset Like a Pro

   When working with data, the first step isn’t analysis or modeling—it’s understanding.Taking time to perform a comprehensive data overview and summary not only highlights potential challenges but also sets the stage for impactful insights. A quick preview can reveal patterns, inconsistencies, and opportunities, helping you approach your dataset with clarity. This post covers the essentials of data overviews, summaries, and previews, providing actionable steps and Python tools to make the process seamless.

## Why Data Overview Matters

Starting data analysis without an overview is like setting sail without checking the weather forecast—you might make progress, but you're unprepared for the challenges ahead. By summarising and previewing your dataset, you can:

- Understand its structure and size.
- Identify missing, duplicate, or problematic data.
- Gain insights into variable types and distributions.

A proper data overview ensures you’re working with clean, well-organized data, saving time and avoiding pitfalls later in the process.

## Automating Overviews with Python
Manually summarizing large datasets can be tedious, but Python makes it easy. In this post, we’ll explore how to streamline the process using custom functions.

In [1]:
import numpy as np
import pandas as pd

In [7]:
train_data=pd.read_csv("dataset.csv")

In [8]:
train_data

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Fungal infection,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fungal infection,itching,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fungal infection,itching,skin_rash,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Fungal infection,itching,skin_rash,nodal_skin_eruptions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,(vertigo) Paroymsal Positional Vertigo,vomiting,headache,nausea,spinning_movements,loss_of_balance,unsteadiness,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4916,Acne,skin_rash,pus_filled_pimples,blackheads,scurring,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4917,Urinary tract infection,burning_micturition,bladder_discomfort,foul_smell_of urine,continuous_feel_of_urine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4918,Psoriasis,skin_rash,joint_pain,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4919,Impetigo,skin_rash,high_fever,blister,red_sore_around_nose,yellow_crust_ooze,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Save these functions into a python file called functions

In [ ]:
def data_overview(data, title):
    overview_analysis = {f'{title}':[data.shape[1], data.shape[0], 
                                     data.isnull().any(axis=1).sum(), 
                                     data.isnull().any(axis=1).sum()/len(data)*100,
                                     data.duplicated().sum(),
                                    data.duplicated().sum()/len(data)*100, 
                                     sum((data.dtypes == 'object') & (data.nunique() > 2)),
                                     sum((data.dtypes == 'object') & (data.nunique() < 3)),
                                     data.select_dtypes(include=['int64', 'float64']).shape[1]
                                    ]}
    overview_analysis=pd.DataFrame(overview_analysis, index=['Columns','Rows','Missing_Values','Missing_Values %',
                                                             'Duplicates', 'Duplicates %','Categorical_variables','Boolean_variables','Numerical_variables']).round(2)
    return overview_analysis




def variables_overview(data):
    variable_details = {
        'unique': data.nunique(),
        'dtype': data.dtypes,
        'null': data.isna().sum(),
        'null %': data.isna().sum() / len(data) * 100,
    }
    variable_details = pd.DataFrame(variable_details)


    # Add a new column 'has_non_alphanumeric' to indicate if there are non-alphanumeric characters
    
    variable_details['has_non_alphanumeric'] = data.apply(lambda col: any(col.apply(lambda x: not str(x).replace(" ", "").isalnum())))
    #variable_details['has_non_alphanumeric'] = data.apply(lambda col: any(col.apply(lambda x: not str(x).isalnum())))

    # Add a new column 'has_digits' to indicate if there are rows containing digits in each column
    variable_details['has_digits'] = data.apply(lambda col: any(col.apply(has_digits)))

    
    return variable_details

In [12]:
from functions import data_overview, variables_overview

In [13]:
data_overview(train_data, "Data_Overview")

                       Data_Overview
Columns                        18.00
Rows                         4920.00
Missing_Values               4848.00
Missing_Values %               98.54
Duplicates                   4616.00
Duplicates %                   93.82
Categorical_variables          17.00
Boolean_variables               1.00
Numerical_variables             0.00

In [14]:
variables_overview(train_data)

            unique   dtype  null     null %  has_non_alphanumeric  has_digits
Disease         41  object     0   0.000000                  True       False
Symptom_1       34  object     0   0.000000                  True       False
Symptom_2       48  object     0   0.000000                  True       False
Symptom_3       54  object     0   0.000000                  True       False
Symptom_4       50  object   348   7.073171                  True       False
Symptom_5       38  object  1206  24.512195                  True       False
Symptom_6       32  object  1986  40.365854                  True       False
Symptom_7       26  object  2652  53.902439                  True       False
Symptom_8       21  object  2976  60.487805                  True       False
Symptom_9       22  object  3228  65.609756                  True       False
Symptom_10      21  object  3408  69.268293                  True       False
Symptom_11      18  object  3726  75.731707                  True       False
Symptom_12      11  object  4176  84.878049                  True       False
Symptom_13       8  object  4416  89.756098                  True       False
Symptom_14       4  object  4614  93.780488                  True       False
Symptom_15       3  object  4680  95.121951                  True       False
Symptom_16       3  object  4728  96.097561                  True       False
Symptom_17       1  object  4848  98.536585                  True       False

In [7]:
import subprocess

def run_command(command):
    """Run a shell command and handle errors."""
    try:
        result = subprocess.run(command, shell=True, check=True, capture_output=True, text=True)
        print(result.stdout)
    except subprocess.CalledProcessError as e:
        print(f"Error: {e.stderr}")
        exit(1)

In [9]:
import subprocess
import os

# Define the repository name
repo_name = "ml-ds"

repo_url = "https://github.com/sisqodataclub/ml-ds.git"  # Change this!

# Step 1: Create a directory and navigate into it
if not os.path.exists(repo_name):
    os.mkdir(repo_name)

# Step 2: Initialize Git repository
run_command(f"git init {repo_name}")

# Step 3: Create a README file
readme_path = os.path.join(repo_name, "README.md")
with open(readme_path, "w") as f:
    f.write(f"# {repo_name}\n")

# Step 4: Add and commit changes
run_command(f"git -C {repo_name} add .")
run_command(f'git -C {repo_name} commit -m "Initial commit"')

# Step 5: Add remote origin and push
run_command(f"git -C {repo_name} remote add origin {repo_url}")
run_command(f"git -C {repo_name} branch -M main")
run_command(f"git -C {repo_name} push -u origin main")

print("✅ Repository initialized and pushed successfully!")

Initialized empty Git repository in C:/Users/fd92u/ml-ds/.git/


[master (root-commit) c6cb755] Initial commit
 1 file changed, 1 insertion(+)
 create mode 100644 README.md



branch 'main' set up to track 'origin/main'.

✅ Repository initialized and pushed successfully!